c

diff --git a/Formula/pod2lib b/Formula/pod2lib
--- a/Formula/pod2lib
+++ b/Formula/pod2lib
@@ -1,3 +1,28 @@
+# Merge Script
+
+# 1
+# Set bash script to exit immediately if any commands fail.
+set -e
+. function.sh
+
+mkdir pod2lib
+cd pod2lib
+
+if [ $1 = "-clean" ]
+then
+rm -f podslist.txt
+get_pod_list_by_local_file 0 #pbxproject截取pods列表
+else
+get_pod_list_by_local_file 1 #本地文件读取pods列表
+fi
+
+main
+
+
+
+
+
+
 
 #本地文件读取pods列表
 function get_local_pods_list()
@@ -170,4 +195,7 @@ fi
 
 
 }
+
+
+
 
